---
features:
  - |
    Implemented variable ``horizon_extra_local_settings`` that allows to
    insert arbitrary parameters defined as a regular mapping inside
    local_settings.py of Horizon. Parameters will be inserted at the end of
    the config file.
